---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: apache
  name: apache 
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: apache
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: apache
      name: apache
    spec:
      containers:
      - name: apache
        image: gceme:1.0.0 
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 80
        resources:
          limits:
            cpu: 200m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 120 
          periodSeconds: 10
          timeoutSeconds: 2               
          failureThreshold: 3
